In [1]:
#creating array from list
import numpy as np
arr_1d=np.array([1,2,3,4,5])
print("arr_1d",arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print("arr_2d",arr_2d)

arr_1d [1 2 3 4 5]
arr_2d [[1 2 3]
 [4 5 6]]


In [2]:
# multiply list and array
py_list=[1,2,3]
print("python list multiplication",py_list*2)
py_array=np.array([2,3,4,5,6])
print("python array multiplication",py_array*2)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [ 4  6  8 10 12]


In [3]:
zeros=np.zeros((3,4))
print("zeros array \n",zeros)
ones=np.ones((2,3))
print("one array \n",ones)
two=np.full((2,4),2)
print("twos array\n",two)

zeros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array 
 [[1. 1. 1.]
 [1. 1. 1.]]
twos array
 [[2 2 2 2]
 [2 2 2 2]]
